server {
    listen 8080 default_server;
    listen [::]:8080 default_server;

    server_name _;
    root /var/www/portal;
    index index.html;

    autoindex on;
    autoindex_exact_size off;
    autoindex_localtime on;

    access_log /var/log/nginx/portal-access.log;
    error_log  /var/log/nginx/portal-error.log;

    location / {
        try_files $uri $uri/ =404;
    }
}
